
server:
  port: 8020
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true    
      
spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: hr
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
  
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
        
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
      
#server:
#  port: 8080
#  servlet:
#    context-path: /
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true    
#      
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/Sups?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: hr
#    password: 1234
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
#  jpa:
#    database: mysql
#    open-in-view: true
#    hibernate:
#      use-new-id-generator-mappings: false
#      ddl-auto: create
#      naming:
#       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      #JPA가 사용하는 기본 넘버링 전략을 사용하지 않는다.
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    properties:
#      format_sql: true
#  jackson:
#    serialization:
#      fail-on-empty-beans: false